### ISSUE TITLE
Action doesn't work for forks (Resource not accessible by integration)

### ISSUE THREAD

**Issue by yukinoda** [monstar-lab-oss/admin-panel-template-reactjs#123]
https://github.com/TimonVS/pr-labeler-action/issues/25

**Comment by yukinoda** [comment]
We can try this

```
name: PR Labeler
on:
  pull_request_target:
    types: [opened]
```

ref: https://github.com/TimonVS/pr-labeler-action/issues/25#issuecomment-891051406
